export const allOrdersFields = [
  { label: "S.No", key: "s_no" },
  { label: "Invoice_ID", key: "invoice_no" },
  { label: "Bill_No", key: "order_id" },
  { label: "Order_ID", key: "order_id" },
  { label: "Order_Status", key: "order_status" },
  { label: "Order_Date", key: "order_date" },
  { label: "Order_Time", key: "order_time" },
  { label: "Sales_Date", key: "delivered_date" },
  { label: "Sales_Time", key: "delivered_time" },
  { label: "Farmer_ID", key: "customer_auth_code" },
  { label: "Famer_Name", key: "customer_name" },
  { label: "Farmer_Billing_Address", key: "farmer_billing_address" },
  { label: "Phone-no", key: "customer_phone_no" },
  { label: "Farmer_Shipping_Address", key: "farmer_Shipping_Address" },
  { label: "Selected_Retailer", key: "selected_retailer" },
  { label: "Selected_Retailer_Erp_Code", key: "retailer_erp_code" },
  { label: "Category", key: "category_name" },
  { label: "Sub_category", key: "subcategory_name" },
  { label: "SKU_Placed", key: "sku_name" },
  { label: "SKU_Code", key: "sku_code" },
  { label: "SKU_Size", key: "order_weight" },
  { label: "Quantity", key: "order_quantity" },
  { label: "Unit_Price ", key: "order_price" },
  { label: "SGST", key: "order_sgst" },
  { label: "CGST ", key: "order_cgst" },
  { label: "Delivery_charge ", key: "delivery_charge" },
  { label: "Delivery_discount ", key: "delivery_discount" },
  { label: "Total_Value", key: "grand_total" },
  { label: "Payment_to", key: "payment_to" },
  { label: "Payment_method", key: "payment_method" },
  { label: "Brand_name", key: "brand_name" },
  { label: "DS margin/Unit", key: "" },
  { label: "Total Margin", key: "" },
  { label: "Payable to Retailer", key: "" },
  { label: "Unique farmer", key: "" },
  { label: "Unique order", key: "" },
  { label: "Unique SKUs", key: "" },
  { label: "Count of SKUS", key: "" },
  { label: "Repeating Farmers", key: "" },
  { label: "Date updated on", key: "" },
  { label: "Helper Column for Identifying repeating farmers", key: "" },
  { label: "Reason Name", key: "reason_name" },
  { label: "Reason Type", key: "" },
  { label: "Other Reason", key: "other_reason" },
];

export const ordersFields = [
  { label: "S.No", key: "s_no" },
  { label: "Invoice_ID", key: "invoice_no" },
  { label: "Bill_No", key: "order_id" },
  { label: "Order_ID", key: "order_id" },
  { label: "Order_Date", key: "order_date" },
  { label: "Order_Time", key: "order_time" },
  { label: "Sales_Date", key: "delivered_date" },
  { label: "Sales_Time", key: "delivered_time" },
  { label: "Farmer_ID", key: "customer_auth_code" },
  { label: "Famer_Name", key: "customer_name" },
  { label: "Farmer_Billing_Address", key: "farmer_billing_address" },
  { label: "Phone-no", key: "customer_phone_no" },
  { label: "Farmer_Shipping_Address", key: "farmer_Shipping_Address" },
  { label: "Selected_Retailer", key: "selected_retailer" },
  { label: "Selected_Retailer_Erp_Code", key: "retailer_erp_code" },
  { label: "Category", key: "category_name" },
  { label: "Sub_category", key: "subcategory_name" },
  { label: "SKU_Placed", key: "sku_name" },
  { label: "SKU_Code", key: "sku_code" },
  { label: "SKU_Size", key: "order_weight" },
  { label: "Quantity", key: "order_quantity" },
  { label: "Unit_Price ", key: "order_price" },
  { label: "SGST", key: "order_sgst" },
  { label: "CGST ", key: "order_cgst" },
  { label: "Delivery_charge ", key: "delivery_charge" },
  { label: "Delivery_discount ", key: "delivery_discount" },
  { label: "Total_Value", key: "grand_total" },
  { label: "Payment_to", key: "payment_to" },
  { label: "Payment_method", key: "payment_method" },
  { label: "Brand_name", key: "brand_name" },
  { label: "DS margin/Unit", key: "" },
  { label: "Total Margin", key: "" },
  { label: "Payable to Retailer", key: "" },
  { label: "Unique farmer", key: "" },
  { label: "Unique order", key: "" },
  { label: "Unique SKUs", key: "" },
  { label: "Count of SKUS", key: "" },
  { label: "Repeating Farmers", key: "" },
  { label: "Date updated on", key: "" },
  { label: "Helper Column for Identifying repeating farmers", key: "" },
  { label: "Reason Name", key: "reason_name" },
  { label: "Reason Type", key: "" },
  { label: "Other Reason", key: "other_reason" },
];
