export const retailerReportFields = [
  { label: "S.No", key: "s_no" },
  { label: "Areas", key: "" },
  { label: "Company Name", key: "company_name" },
  { label: "Retailer Name", key: "retailer_name" },
  { label: "Phone No", key: "phone_no" },
];

export const retailerFields = [
  { label: "S.No", key: "s_no" },
  { label: "Company Name", key: "company_name" },
  { label: "Retailer Name", key: "retailer_name" },
  { label: "Type", key: "type" },
  { label: "Zone Name", key: "zone_name" },
  { label: "ERP Code", key: "erp_code" },
  { label: "Email Id", key: "email_id" },
  { label: "Phone Number", key: "phone_no" },
  { label: "Address", key: "address" },
  { label: "State", key: "state" },
  { label: "District", key: "district" },
  { label: "City", key: "city" },
  { label: "Pincode", key: "pincode" },
  { label: "Jurisdiction", key: "jurisdiction" },
  { label: "Terms Conditions", key: "terms_conditions" },
  { label: "GST Number", key: "gst_number" },
  { label: "Pan Number", key: "pan_no" },
  { label: "Default Credit Limit", key: "default_credit_limit" },
  { label: "Default Credit Period", key: "default_credit_period" },
  { label: "Distributor Level", key: "distributor_level" },
  { label: "Subzone id", key: "subzone_id" },
];

export const retailerSKUPricingFields = [
  { label: "S.No", key: "s_no" },
  { label: "sku_name", key: "sku_name" },
  { label: "sku_name_kannada", key: "sku_name_kannada" },
  { label: "sku_code", key: "sku_code" },
  { label: "category", key: "subcategory_name" },
  { label: "subcategory", key: "subcategory_image" },
  { label: "brand", key: "brand_name" },
  { label: "mrp", key: "mrp" },
  { label: "price", key: "price" },
  { label: "sale_price", key: "sale_price" },
  { label: "weight", key: "weight" },
  { label: "dimension", key: "dimension" },
  { label: "units_per_case", key: "units_per_case" },
  { label: "package", key: "package" },
];
