export const retailerReportFields = [
  { label: "S.No", key: "s_no" },
  { label: "Areas", key: "" },
  { label: "Company Name", key: "company_name" },
  { label: "Retailer Name", key: "retailer_name" },
  { label: "Phone No", key: "phone_no" },
];

export const retailerFields = [
  { label: "S.No", key: "s_no" },
  { label: "Retailer Id", key: "retailer_id" },
  { label: "auth code", key: "auth_code" },
  { label: "Company Name", key: "company_name" },
  { label: "Retailer Name", key: "retailer_name" },
  { label: "Type", key: "type" },
  { label: "Zone Name", key: "zone_name" },
  { label: "ERP Code", key: "erp_code" },
  { label: "Email Id", key: "email_id" },
  { label: "Phone Number", key: "phone_no" },
  { label: "Address", key: "address" },
  { label: "State", key: "state" },
  { label: "District", key: "district" },
  { label: "City", key: "city" },
  { label: "Pincode", key: "pincode" },
  { label: "Jurisdiction", key: "jurisdiction" },
  { label: "Terms Conditions", key: "terms_conditions" },
  { label: "GST Number", key: "gst_number" },
  { label: "Pan Number", key: "pan_no" },
  { label: "Default Credit Limit", key: "default_credit_limit" },
  { label: "Default Credit Period", key: "default_credit_period" },
  { label: "Distributor Level", key: "distributor_level" },
  { label: "Subzone id", key: "subzone_id" },
];
